### ISSUE TITLE
[프론트] 메인 페이지 제작

### ISSUE THREAD

**Issue by gene-ss** [FileGround-CloudComputing/FileGround-Front#1]
## GOAL
- 동작 없는 메인 페이지 제작

## TODO
- [x] 3가지 옵션(그라운드 생성, 그라운드 접속, 그라운드 목록) 껍데기 만들기

- [x] 설정 페이지 접속하는 옵션 만들기

- [x] 메인 페이지 그라운드 목록
